server:
  port: 1218
  error:
    include-message: always
    include-binding-errors: always

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    password: 1218
    url: jdbc:mysql://localhost:3306/graduation_project
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  #    show-sql: true
  app:
    jwtSecret: hiImRiham12
    jwtExpirationMs: 121800000


logging:
  level:
    org:
      springframework:
        security: DEBUG